services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: expvis
      MYSQL_DATABASE: expvis
      MYSQL_USER: expvis
      MYSQL_PASSWORD: expvis
    volumes:
      - mariadb_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      
  expvis:
    build:
      context: ${DAL_REPO_PATH}
      dockerfile: ${DAL_REPO_PATH}/Dockerfile
    environment:
      NODE_ENV: local
      MYSQL_USER: expvis
      MYSQL_PASSWORD: expvis
      MYSQL_DATABASE: expvis
      MYSQL_HOST: extremexp-dal-mariadb-1
      ELASTICSEARCH_HOST: http://extremexp-dal-elasticsearch-1:9200
      DMS_PATH: /app/services/dms
    ports:
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
    depends_on:
      - mariadb
      - elasticsearch
    volumes:
      - ${DAL_REPO_PATH}/server/knex/migrations:/app/knex/migrations 
    command: >
      /bin/bash -c "
      ./wait-for-it.sh extremexp-dal-mariadb-1:3306 --timeout=60 --strict &&
      ./wait-for-it.sh extremexp-dal-elasticsearch-1:9200 --timeout=60 --strict &&
      node /app/server/index.js
      "

volumes:
  mariadb_data:
  elasticsearch_data:
