java:
  path: "java"

mysql:
  host: localhost
  user: expvis
  password: expvis
  database: expvis

partners:
  namespace: 1

# Enable to use Redis session cache or disable if Redis is not installed
redis:
  enabled: false
  host: localhost
  port: 6379
  db: 5
  # Uncomment if your Redis installation requires a password
  # password=""
